insert into PRODUCT (name, cost) VALUES ('Булочки из маны', 30.5);
insert into PRODUCT (name, cost) VALUES ('Кишка великана Николая', 110);
insert into PRODUCT (name, cost) VALUES ('Крендель судьбы', 5.99);
insert into PRODUCT (name, cost) VALUES ('Загадочный пирог', 14.88);
insert into PRODUCT (name, cost) VALUES ('Стиранная пастила', 3.5);
insert into PRODUCT (name, cost) VALUES ('Красная заварушка', 1.5);
insert into PRODUCT (name, cost) VALUES ('Жирная солфетка', 0.5);

insert into USERS (name) values ('Виктор');
insert into USERS (name) values ('Пиктор');
insert into USERS (name) values ('Лектор');
insert into USERS (name) values ('Гектор');
insert into USERS (name) values ('Вектор');
insert into USERS (name) values ('Сектор');
insert into USERS (name) values ('Лектор');
insert into USERS (name) values ('Вася');

insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (1, 1, 30.5);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (1, 4, 14.88);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (2, 2, 110);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (2, 5, 3.5);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (2, 7, 0.5);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (3, 1, 30.5);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (4, 6, 1.5);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (4, 3, 5.99);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (4, 3, 5.99);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (5, 7, 0.5);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (5, 6, 1.5);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (5, 5, 3.5);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (5, 4, 14.88);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (5, 3, 5.9);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (5, 2, 110);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (5, 1, 30.5);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (6, 1, 30.5);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (6, 2, 110);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (6, 2, 110);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (6, 2, 110);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (6, 2, 110);
insert into USERS_PRODUCT (userid, productid, ex_actual_cost) VALUES (6, 7, 0.5);