insert into PRODUCT (name, cost) VALUES ('Булочки из маны', 30.5);
insert into PRODUCT (name, cost) VALUES ('Кишка великана Николая', 110);
insert into PRODUCT (name, cost) VALUES ('Крендель судьбы', 5.99);
insert into PRODUCT (name, cost) VALUES ('Загадочный пирог', 14.88);
insert into PRODUCT (name, cost) VALUES ('Стиранная пастила', 3.5);
insert into PRODUCT (name, cost) VALUES ('Красная заварушка', 1.5);
insert into PRODUCT (name, cost) VALUES ('Жирная солфетка', 0.5);
insert into PRODUCT (name, cost) VALUES ('Чайная гуща', 0.1);
insert into PRODUCT (name, cost) VALUES ('Виноградкая корка', 10.1);
insert into PRODUCT (name, cost) VALUES ('Неожиданный поворот', 10.1);
insert into PRODUCT (name, cost) VALUES ('Фирменные булочки', 30.5);
insert into PRODUCT (name, cost) VALUES ('Натоптанные пирожки', 110);
insert into PRODUCT (name, cost) VALUES ('Порошковые мюсли', 5.99);
insert into PRODUCT (name, cost) VALUES ('Загадочный стих', 14.88);
insert into PRODUCT (name, cost) VALUES ('Стиранная жвачка', 3.5);
insert into PRODUCT (name, cost) VALUES ('Красная настойка', 1.5);
insert into PRODUCT (name, cost) VALUES ('То, что не надо брать', 0.5);
insert into PRODUCT (name, cost) VALUES ('Кофир 2.0', 0.1);
insert into PRODUCT (name, cost) VALUES ('Прикус', 10.1);
insert into PRODUCT (name, cost) VALUES ('Новый керндель', 10.1);

insert into USER (name) values ('Виктор');
insert into USER (name) values ('Пиктор');
insert into USER (name) values ('Лектор');
insert into USER (name) values ('Гектор');
insert into USER (name) values ('Вектор');
insert into USER (name) values ('Сектор');
insert into USER (name) values ('Лектор');
insert into USER (name) values ('Вася');

insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (1, 1, 30.5);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (1, 4, 14.88);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (2, 2, 110);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (2, 2, 100);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (2, 2, 80);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (2, 2, 90);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (2, 5, 3.5);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (2, 7, 0.5);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (3, 1, 30.5);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (4, 6, 1.5);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (4, 3, 5.99);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (4, 3, 5.99);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (5, 7, 0.5);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (5, 6, 1.5);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (5, 5, 3.5);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (5, 4, 14.88);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (5, 3, 5.9);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (5, 2, 110);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (5, 1, 30.5);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (6, 1, 30.5);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (6, 2, 110);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (6, 2, 110);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (6, 2, 110);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (6, 2, 110);
insert into USERS_PRODUCTS (user_id, product_id, ex_actual_cost) VALUES (6, 7, 0.5);